-- AlterTable
ALTER TABLE "public"."report" ADD COLUMN     "business_datacount_scope_one" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "business_datacount_scope_three" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "business_datacount_scope_two" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "business_scope_one" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "business_scope_three" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "business_scope_two" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "business_total_emissions" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "completed_sections" INTEGER DEFAULT 0,
ADD COLUMN     "human_datacount_scope_one" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "human_datacount_scope_three" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "human_datacount_scope_two" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "human_scope_one" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "human_scope_three" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "human_scope_two" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "human_total_emissions" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "leadership_datacount_scope_one" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "leadership_datacount_scope_three" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "leadership_datacount_scope_two" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "leadership_scope_one" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "leadership_scope_three" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "leadership_scope_two" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "leadership_total_emissions" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "total_sections" INTEGER DEFAULT 100;
