export const sectorsWithIndustries = [
  {
    name: 'Consumer Goods',
    sasbCode: 'SASB-CG',
    description: 'Covers industries that produce or sell consumer goods and services, including retail, apparel, household products, and leisure services.',
    industries: [
      { name: 'Apparel, Accessories & Footwear', code: 'CG-AA' },
      { name: 'Appliance Manufacturing', code: 'CG-AM' },
      { name: 'Building Products & Furnishings', code: 'CG-BF' },
      { name: 'E-Commerce', code: 'CG-EC' },
      { name: 'Household & Personal Products', code: 'CG-HP' },
      { name: 'Multiline and Specialty Retailers & Distributors', code: 'CG-MR' },
      { name: 'Toys & Sporting Goods', code: 'CG-TS' },
    ],
  },
  {
    name: 'Extractives & Minerals Processing',
    sasbCode: 'SASB-EM',
    description: 'Includes industries involved in the exploration, extraction, and processing of natural resources such as oil, gas, metals, and minerals.',
    industries: [
      { name: 'Coal Operations', code: 'EM-CO' },
      { name: 'Construction Materials', code: 'EM-CM' },
      { name: 'Iron & Steel Producers', code: 'EM-IS' },
      { name: 'Metals & Mining', code: 'EM-MM' },
      { name: 'Oil & Gas - Exploration & Production', code: 'EM-EP' },
      { name: 'Oil & Gas - Midstream', code: 'EM-MD' },
      { name: 'Oil & Gas - Refining & Marketing', code: 'EM-RM' },
      { name: 'Oil & Gas - Services', code: 'EM-SV' },
    ],
  },
  {
    name: 'Financials',
    sasbCode: 'SASB-FN',
    description: 'Covers industries that provide financial services including banking, insurance, asset management, investment services, and consumer finance.',
    industries: [
      { name: 'Asset Management & Custody Activities', code: 'FN-AC' },
      { name: 'Commercial Banks', code: 'FN-CB' },
      { name: 'Consumer Finance', code: 'FN-CF' },
      { name: 'Insurance', code: 'FN-IN' },
      { name: 'Investment Banking & Brokerage', code: 'FN-IB' },
      { name: 'Mortgage Finance', code: 'FN-MF' },
      { name: 'Security & Commodity Exchanges', code: 'FN-EX' },
    ],
  },
  {
    name: 'Food & Beverage',
    sasbCode: 'SASB-FB',
    description: 'Includes industries engaged in the production, processing, and distribution of food, beverages, and agricultural products.',
    industries: [
      { name: 'Agricultural Products', code: 'FB-AP' },
      { name: 'Alcoholic Beverages', code: 'FB-AB' },
      { name: 'Food Retailers & Distributors', code: 'FB-FR' },
      { name: 'Meat, Poultry & Dairy', code: 'FB-MP' },
      { name: 'Non-Alcoholic Beverages', code: 'FB-NB' },
      { name: 'Processed Foods', code: 'FB-PF' },
      { name: 'Restaurants', code: 'FB-RN' },
      { name: 'Tobacco', code: 'FB-TB' },
    ],
  },
  {
    name: 'Health Care',
    sasbCode: 'SASB-HC',
    description: 'Includes industries that provide healthcare services, medical equipment, pharmaceuticals, and biotechnology solutions.',
    industries: [
      { name: 'Biotechnology & Pharmaceuticals', code: 'HC-BP' },
      { name: 'Drug Retailers', code: 'HC-DR' },
      { name: 'Health Care Delivery', code: 'HC-DY' },
      { name: 'Health Care Distributors', code: 'HC-DI' },
      { name: 'Managed Care', code: 'HC-MC' },
      { name: 'Medical Equipment & Supplies', code: 'HC-MS' },
    ],
  },
  {
    name: 'Infrastructure',
    sasbCode: 'SASB-IF',
    description: 'Includes industries responsible for the development, operation, and management of physical infrastructure such as real estate, utilities, and construction.',
    industries: [
      { name: 'Electric Utilities & Power Generators', code: 'IF-EU' },
      { name: 'Engineering & Construction Services', code: 'IF-EN' },
      { name: 'Gas Utilities & Distributors', code: 'IF-GU' },
      { name: 'Home Builders', code: 'IF-HB' },
      { name: 'Real Estate', code: 'IF-RE' },
      { name: 'Real Estate Services', code: 'IF-RS' },
      { name: 'Waste Management', code: 'IF-WM' },
      { name: 'Water Utilities & Services', code: 'IF-WU' },
    ],
  },
  {
    name: 'Renewable Resources & Alternative Energy',
    sasbCode: 'SASB-RR',
    description: 'Comprises industries involved in renewable energy generation and the sustainable management of natural resources such as agriculture, forestry, and bioenergy.',
    industries: [
      { name: 'Biofuels', code: 'RR-BI' },
      { name: 'Forestry Management', code: 'RR-FM' },
      { name: 'Fuel Cells & Industrial Batteries', code: 'RR-FC' },
      { name: 'Pulp & Paper Products', code: 'RR-PP' },
      { name: 'Solar Technology & Project Developers', code: 'RR-ST' },
      { name: 'Wind Technology & Project Developers', code: 'RR-WT' },
    ],
  },
  {
    name: 'Resource Transformation',
    sasbCode: 'SASB-RT',
    description: 'Includes industries that transform raw materials into finished or intermediate goods, such as chemicals, industrial manufacturing, and materials processing.',
    industries: [
      { name: 'Aerospace & Defense', code: 'RT-AE' },
      { name: 'Chemicals', code: 'RT-CH' },
      { name: 'Containers & Packaging', code: 'RT-CP' },
      { name: 'Electrical & Electronic Equipment', code: 'RT-EE' },
      { name: 'Industrial Machinery & Goods', code: 'RT-IG' },
    ],
  },
  {
    name: 'Services',
    sasbCode: 'SASB-SV',
    description: 'Covers industries that provide commercial, professional, and consumer services such as consulting, education, and waste management.',
    industries: [
      { name: 'Advertising & Marketing', code: 'SV-AM' },
      { name: 'Advisory', code: 'SV-AD' },
      { name: 'Casinos & Gaming', code: 'SV-CG' },
      { name: 'Education', code: 'SV-ED' },
      { name: 'Hotels & Lodging', code: 'SV-HL' },
      { name: 'Leisure Facilities', code: 'SV-LF' },
      { name: 'Media & Entertainment', code: 'SV-ME' },
      { name: 'Professional & Commercial Services', code: 'SV-PC' },
    ],
  },
  {
    name: 'Technology & Communications',
    sasbCode: 'SASB-TC',
    description: 'Includes industries focused on software, hardware, telecommunications, media, and digital services.',
    industries: [
      { name: 'Electronic Manufacturing Services & Original Design Manufacturing', code: 'TC-EM' },
      { name: 'Hardware', code: 'TC-HW' },
      { name: 'Internet Media & Services', code: 'TC-IM' },
      { name: 'Semiconductors', code: 'TC-SC' },
      { name: 'Software & IT Services', code: 'TC-SI' },
      { name: 'Telecommunication Services', code: 'TC-TL' },
    ],
  },
  {
    name: 'Transportation',
    sasbCode: 'SASB-TR',
    description: 'Comprises industries involved in the movement of goods and people, including aviation, shipping, rail, trucking, and logistics services.',
    industries: [
      { name: 'Air Freight & Logistics', code: 'TR-AF' },
      { name: 'Airlines', code: 'TR-AL' },
      { name: 'Auto Parts', code: 'TR-AP' },
      { name: 'Automobiles', code: 'TR-AU' },
      { name: 'Car Rental & Leasing', code: 'TR-CR' },
      { name: 'Cruise Lines', code: 'TR-CL' },
      { name: 'Marine Transportation', code: 'TR-MT' },
      { name: 'Rail Transportation', code: 'TR-RA' },
      { name: 'Road Transportation', code: 'TR-RO' },
    ],
  },
];
