/** The 38 assessment form group keys used for progress tracking. */
export const ALL_GROUP_KEYS = [
  "environment.ghg.scope1.stationarySources",
  "environment.ghg.scope1.mobileSources",
  "environment.ghg.scope1.processEmissions",
  "environment.ghg.scope1.fugitiveEmissions",
  "environment.ghg.scope2.locationBased",
  "environment.ghg.scope2.marketBased",
  "environment.ghg.scope3.upstream",
  "environment.ghg.scope3.downstream",
  "environment.airQuality.airPollutantEmissions",
  "environment.waterManagement.waterAndProducedWaterManagement.freshwaterWithdrawals",
  "environment.waterManagement.waterAndProducedWaterManagement.producedWaterManagement",
  "environment.waterManagement.hydraulicFracturingImpacts.waterQualityImpacts",
  "environment.waterManagement.hydraulicFracturingImpacts.chemicalDisclosure",
  "environment.biodiversityImpact.environmentalManagement.hydrocarbonSpills",
  "environment.biodiversityImpact.environmentalManagement.environmentalManagementPolicies",
  "environment.biodiversityImpact.environmentalManagement.reservesInSensitiveAreas",
  "foundationalData.activityMetrics.productionVolumes",
  "foundationalData.activityMetrics.offshoreSites",
  "foundationalData.activityMetrics.terrestrialSites",
  "socialCapital.securityHumanRights.operationsInConflictZones",
  "socialCapital.securityHumanRights.reservesInNearIndigenousLand",
  "socialCapital.securityHumanRights.humanRightsEngagementProcesses",
  "socialCapital.communityRelations.communityRiskOpportunityManagement",
  "socialCapital.communityRelations.hcdtContribution",
  "socialCapital.communityRelations.communityDisputeResolution",
  "socialCapital.communityRelations.operationalDelays",
  "humanCapital.workforceHealthSafety",
  "humanCapital.riskAndOpportunityManagement.healthAndSafetyPerformance",
  "businessModel.reservesValuation.reservesSensitivity",
  "businessModel.reservesValuation.embeddedCarbon",
  "businessModel.reservesValuation.renewableEnergyInvestment",
  "businessModel.reservesValuation.capitalExpenditureStrategy",
  "businessModel.businessEthics.reservesCountriesCorruptionRisk",
  "businessModel.businessEthics.antiCorruptionManagement",
  "leadershipGovernance.criticalIncidentRiskManagement.processSafetyEvents",
  "leadershipGovernance.criticalIncidentRiskManagement.catastrophicRiskManagementSystems",
  "leadershipGovernance.legalRegulatoryEnvironment.boardManagementOversight",
  "leadershipGovernance.legalRegulatoryEnvironment.publicPolicyEngagement",
] as const;

export const TOTAL_GROUP_COUNT = ALL_GROUP_KEYS.length;
